### ISSUE TITLE
Enhancement:  DDR/StepMania/ Rhythm game

### ISSUE THREAD

**Issue by Twitch0815** [zerojay/RetroPie-Extra#111]
https://github.com/openitg/openitg
Open ITG looks like a possibility
or the one you mentioned earlier, 
https://bitbucket.org/PhracturedBlue/stepmania-gles2

But really ay DDR esque type game that can be ported and paired with a USB Dance Pad.

**Comment by RetroPieNerd** [comment]
I would really like to see this being ported to the Pi.

**Comment by zerojay** [comment]
I have given various versions of Stepmania a shot. It looks like Stepmania 3.9 is the best bet at this point. I think with a tweak or two, I'll get it compiled and we'll see how it works out.

**Comment by andywarburton** [comment]
Would PyDance be a good option? https://icculus.org/pyddr/

I found it on this thread on the Raspberry Pi forum https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=51794 (may provide more inspiration for future extras)

**Comment by zerojay** [comment]
I'll try to take a look at it. I'm kind of wrapped up as I'm about to be moving to a new city for a new job so my time over the next month or so is going to be very limited, so if you want something, it's best to post it as its own issue with links, info and I'll get to it when I can. I'm basically using the issue tracker here for organization in the meantime.

**Comment by zerojay** [comment]
PyDance is a go. https://twitter.com/zerojay/status/722121993596710914

**Comment by andywarburton** [comment]
Awesome!!!! Nice one!

**Comment by zerojay** [comment]
Pydance has been added to the repository as of commit https://github.com/zerojay/RetroPie-Extra/commit/e86e4b1e06253e05262218dee963fc52c845477a

**Comment by andywarburton** [comment]
sweet! I got FoFix working last night but I need to see how to add music and get the speakers hooked up on my arcade :)

**Comment by Japetusgr** [comment]
Tried Pydance but can't seem to run it through emulationstation. Start menu is ok, but when entering actual game screen, pydance crashes with an error I don't have time to see as the screen goes black. Is there a log created somewhere where I can search for the error message? When starting the game from command prompt 'python pydance. py' runs correctly.

**Comment by ttheuer** [comment]
I have exactly the same problem as @Japetusgr.

**Comment by mbenkmann** [comment]
I found the reason why it doesn't work when started from emulationstation.  In dance.py there are these 2 lines

`print songdata.title.encode(sys.stdout.encoding, "replace"), "by",`
`print songdata.artist.encode(sys.stdout.encoding, "replace")`

However when stdout is not a terminal (i.e. when it' being redirected into a file), the .encoding attribute is empty which encode() doesn't like. If you replace sys.stdout.encoding with "UTF-8", it works fine. 
Is anyone aware of an active maintainer for pydance to contact about this bug? Otherwise it would be simple to add a small patch to the retropie install script for pydance.

**Comment by mbenkmann** [comment]
I've reached the pydance maintainer. We may get an official release with the fix at some point. I will also work on some other issues I've noticed (e.g. duplicate entries in the song list when both an .sm and a .dwi are present). In particular I would like some better input integration. Is there a Python module that works with libretro/retropad?

**Comment by Japetusgr** [comment]
Has the issue been addressed yet?

**Comment by mbenkmann** [comment]
There's nothing from the package maintainer, but I've done considerable work on pydance which you can find at

https://github.com/mbenkmann/pydance

My aim was to provide an out-of-the-box experience for retropie, including automatic import of retropad controller configurations. But as these things go other things came up and I interrupted my work. I think the current state of my tree should work fine EXCEPT for the input configuration dialog which is non-functional. However it does have functionality for learning dance pad buttons automatically, so if you have a dance pad you should be able to use it right away. Otherwise you would have to manually change the button mapping in the source code.
One really nice feature my version of pydance has is that it can learn the audio delay which seems to be quite significant on retropie, so that all notes are slightly off-beat.

**Comment by zerojay** [comment]
I'm going to try updating the port to your source and see how it goes.
