### ISSUE TITLE
Streets of rage Remake

### ISSUE THREAD

**Issue by 0uro** [zerojay/RetroPie-Extra#183]
Hello,
- fresh setup, starting from berryboot
- updated from retropie 3.6 to 4.0
- installed your extra scripts by following your instructions
- downloaded game files + patchs
- put everything in /opt/retropie/ports/sorr

When I start the game, the screen goes black, the music starts for a few seconds and the game crashes. Screen remains black all the time.
- permissions on savegame folder seems ok
- tried forcing debug from bennugd by modifying command : "./bgdi-330 -d ./SorR.dat; popd &> /home/pi/LOGS.txt" but LOGS.txt is just empty.

**Comment by zerojay** [comment]
Please try the updated sorr.sh script and see if it works for you. Just added a missing dependency on libsdl-mixer1.2.

**Comment by 0uro** [comment]
Ok, updated it.
libsdl-mixer1.2 and dependencies were actually already installed.
I still get the same symptoms as before.
When I launch it from the tty (without emulationstation) the game shows up, but when it reaches the leaf it just crashes, output on /dev/shm/runcommand.log : 
/opt/retropie/supplementary/runcommand/runcommand.sh: line 827:  1155 Segmentation fault      ./bgdi-330 -d ./SorR.dat

With gdb I get this :
Program received signal SIGSEGV, Segmentation fault.
0x0005d9ec in gr_make_trans_table () at g_pal.c:742
742	g_pal.c: No such file or directory.

To me it looks like the origin lies in bgdi itself, but I'm not a pro ^^

Anyway, thanks for your help :)

**Comment by MentalPictures** [comment]
Hello, thank you for the great work. I seem to have the same problem as 0uro. 

Sorr crashes just as the camera starts to move away from the leaf. Anyone had this problem and managed to solve it?

**Comment by DieDaily** [comment]
I'm having the same exact issue as MentalPictures above. Mine locks up on the leaf in the intro as well.

Thanks for getting this ported and working to begin with. If you are able to fix it, I'd love to play it on my Pi.

**Comment by ljmcdonald86** [comment]
I'm having the same issue, it crashes as it pans up during the leaf scene.

**Comment by zerojay** [comment]
Pretty sure this is because you are using the Windows version of the files and you should not be.

**Comment by 0uro** [comment]
I tried again, using different game sources like that one : https://aur.archlinux.org/packages/streetsofrageremake/

But same problem

**Comment by ljmcdonald86** [comment]
I was indeed using Windows files, but after removing sorr, re-adding it, and then putting the linux files into place, I am having the same issue. That said, the log file now shows more info:

`Parameters: 
Executing: pushd /opt/retropie/ports/sorr; ./bgdi-330 ./SorR.dat; popd
/opt/retropie/ports/sorr ~
Couldn't load mod/music/11.ogg: Module format not recognized
Play song called with invalid handle/opt/retropie/supplementary/runcommand/runcommand.sh: line 947: 12446 Segmentation fault      ./bgdi-330 ./SorR.dat
~`

So it seems to be having problems running the ogg audio file. I think I have all the relevant libs including libsdl-mixer1.2 so not sure what the problem is.

**Comment by ljmcdonald86** [comment]
@0uro 
So I finally got this working over the weekend. I updated Retropie to 4.2 (probably didn't have anything to do with it), uninstalled the sorr package, and started over with a fresh install, with the files found here: https://launchpad.net/~ubuntugames/+archive/ubuntu/games/+sourcepub/4644635/+listing-archive-extra

Whichever linux files I had found earlier were not working. Unfortunately it's hard to find the linux files for sorr anymore, as almost everywhere you look links to ubuntugames.org, which appears to have been down for a few months now.

**Comment by zerojay** [comment]
a) Must use Linux versions of the files. I was just able to find them because I just got a new pi (my old one died) and I was able to play.
b) You absolutely *must* choose * Fast (Full Screen) at the top of the list of video modes. If you do not, the game crashes at the leaf. This is an engine issue, nothing I can do anything about.
