### ISSUE TITLE
Chocolate Doom Install Problem

### ISSUE THREAD

**Issue by symbios24** [zerojay/RetroPie-Extra#213]
Hello i`m trying to install chocolate doom through the Retropie-Extra Scripts as i did it several times before n the past with success, but the install keeps failing i`m getting this error "/home/pi/retropie-setup/tmp/build/chocolate-doom/src/chocolate-strife not found"   can this be fixed?

Thanks

**Comment by jmtd** [comment]
You also reported this upstream, here, https://github.com/chocolate-doom/chocolate-doom/issues/916 with a build log comment, but the problem is with this script

We switched the default branch for chocolate-doom repo to "sdl2-branch" which uses SDL2 instead of SDL1. The scriptmodules/ports/chocolate-doom.sh script (around line 12) needs the sdl1.2* packages changed to sdl2* equivalents. I'd also suggest libpng-dev and libsamplerate-dev which are optional but useful dependencies (libpng especially).
