### ISSUE TITLE
Manaplus client

### ISSUE THREAD

**Issue by symbios24** [zerojay/RetroPie-Extra#233]
Hello, manaplus client is not working it simply returns to emulationstation after run.

**Comment by zerojay** [comment]
I just installed and compiled it and it runs fine. You likely needed to run dpkg-reconfigure xserver-xorg-legacy and then select to allow all users to be able to run X. At that point, it should run from emulationstation. This is mentioned in the readme at the front of this repo.

Next time, please take a look at /dev/shm/runcommand.log to see what errors are produced so that it can more easily be figured out.

**Comment by symbios24** [comment]
if i install the client with sudo apt-get install manaplus it works great without the command dpkg-reconfigure xserver-xorg-legacy that is not working it says warning: start and stop actions are no longer supported; falling back to defaults.anyway thanks
