### ISSUE TITLE
CaveStory Never start

### ISSUE THREAD

**Issue by Darknior** [zerojay/RetroPie-Extra#247]
I have try CaveStory stand alone from here and the LIBRETRO version to compare.
I have try many many games versions and it never start in stand alone, it always come back to ES after black screen.
The LIBRETRO one is working fine in english, i have speak with the developers and they know now why it crash in french, maybe they will fix it one day.
Your stand alone like all the other version is not working in French too if i understand. No real interest to keep it i think.
I wish the RETROARCH version will also add SaveState :)

**Comment by zerojay** [comment]
Please try running it and pasting in the contents of runcommand.log after.

**Comment by Darknior** [comment]
Arg i don't know there is this LOG file. found /dev/shm/runcommand.log
I have remove games now, but i will do it later if i can.

**Comment by zerojay** [comment]
Yes, anytime you run into any issues, /dev/shm/runcommand.log is what I'll need to see what's happening.

**Comment by zerojay** [comment]
I looked at this installer for the first time in a long time and I didn't like the way the data stuff was laid out. I've changed the script to just use data found in /opt/retropie/ports/nxengine/data instead of using a folder in the roms directory.

https://github.com/zerojay/RetroPie-Extra/commit/f94d2de284cacd94d3ba10a9636631841d28347a
