### ISSUE TITLE
Mayhem missing?

### ISSUE THREAD

**Issue by Theonian** [zerojay/RetroPie-Extra#315]
Can't seem to find Mayhem in the package list, though it appears on the "Included software" list on the website. Has it been left out?

**Comment by zerojay** [comment]
Hi. I think you missed the note at the very top of the README file for this archive. Nothing here is expected to work anymore since about Retropie 4.3 when they made major changes to how everything worked and I didn't have time/desire to work on it any longer thanks to some extremely entitled people in the RetroPie community.

But good news, after being away from Retropie for a few years, I just bought a Pi 4 and am in the middle of setting it up so I'll have the bug to get this stuff working again. I may not do everything, but we'll see. No promises.

**Comment by Theonian** [comment]
Oh, I see!
Very sorry to hear that. I saw some of your posts on the forum, and gee,
seems like a hostile environment.

Anyway, I'd love to try some of the stuff if you do end up fixing it for
the new versions!

Keep up the good work!

man. 24. aug. 2020 kl. 21:10 skrev zerojay <notifications@github.com>:

**Comment by zerojay** [comment]
Here's the reason it was moved: https://github.com/zerojay/RetroPie-Extra/commit/a34ef08709861bb402402fd8339515059b8107a3#diff-85d09d266b45472bfc9f5c862f07becc

I'll give it a shot though.

**Comment by zerojay** [comment]
Mayhem is still broken and still needs to be fixed upstream as it asserts during startup. The script that checks how much ram is allocated to the GPU is also broken, but the main issue is Allegro asserts on start. As mentioned in issue #280, this will need to be fixed upstream as there is nothing I can do for this.
