### ISSUE TITLE
Maelstrom Port Install - Ubuntu Retropie

### ISSUE THREAD

**Issue by macollin123** [zerojay/RetroPie-Extra#316]
Greetings -

I am hoping to possibly get some assistance with getting Maelstrom working on a Ubuntu install of Retropie. I feel like I am getting close to success, but it's not installing correctly. I commented out the !x86 flag so the script would show up in the experimental section of the Retropie setup script. Obviously this was there for a reason so I am wondering if this is the problem. 

When I do install from source in the setup script I receive the attached error message. 

![image](https://user-images.githubusercontent.com/68788606/91742646-910d4d80-eb84-11ea-8685-19d6e2ab02dc.png)

The log can be found here:  https://pastebin.pl/view/embed/b56c3ac9

Thank you in advance for any help.

**Comment by zerojay** [comment]
Unfortunately, I am unable to compile this myself. I have many of the same warnings you do but my errors are different. This will need to be fixed by upstream, I'm pretty certain. Unfortunately, this means that Maelstrom will get demoted to the RetroPie-Extra-Unstable repository.

g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"Maelstrom\" -DVERSION=\"3.0.6\" -I.     -march=armv8-a+crc -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard -O2  -march=armv8-a+crc -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard -O2 -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -I. -I./netlogic -I./screenlib -I./maclib -DLIBDIR=\"/usr/local/games/Maelstrom\" -c -o myerror.o myerror.cpp
In file included from main.cpp:14:
buttonlist.h: In member function ‘void ButtonList::Add_Button(Uint16, Uint16, Uint16, Uint16, void (*)())’:
buttonlist.h:19:10: error: using typedef-name ‘ButtonList::button’ after ‘struct’
   struct button *belem;
          ^~~~~~
buttonlist.h:62:4: note: ‘ButtonList::button’ has a previous declaration here
  } button;
    ^~~~~~
buttonlist.h:21:16: error: cannot convert ‘ButtonList::button*’ to ‘int*’ in assignment
   for ( belem=&button_list; belem->next; belem=belem->next );
                ^~~~~~~~~~~
buttonlist.h:21:36: error: request for member ‘next’ in ‘* belem’, which is of non-class type ‘int’
   for ( belem=&button_list; belem->next; belem=belem->next );
                                    ^~~~
buttonlist.h:21:55: error: request for member ‘next’ in ‘* belem’, which is of non-class type ‘int’
   for ( belem=&button_list; belem->next; belem=belem->next );
                                                       ^~~~
buttonlist.h:22:10: error: request for member ‘next’ in ‘* belem’, which is of non-class type ‘int’
   belem->next = new button;
          ^~~~
buttonlist.h:23:18: error: request for member ‘next’ in ‘* belem’, which is of non-class type ‘int’
   belem = belem->next;
                  ^~~~
buttonlist.h:24:10: error: request for member ‘x1’ in ‘* belem’, which is of non-class type ‘int’
   belem->x1 = x;
          ^~
buttonlist.h:25:10: error: request for member ‘y1’ in ‘* belem’, which is of non-class type ‘int’
   belem->y1 = y;
          ^~
buttonlist.h:26:10: error: request for member ‘x2’ in ‘* belem’, which is of non-class type ‘int’
   belem->x2 = x+width;
          ^~
buttonlist.h:27:10: error: request for member ‘y2’ in ‘* belem’, which is of non-class type ‘int’
   belem->y2 = y+height;
          ^~
buttonlist.h:28:10: error: request for member ‘callback’ in ‘* belem’, which is of non-class type ‘int’
   belem->callback = callback;
          ^~~~~~~~
buttonlist.h:29:10: error: request for member ‘next’ in ‘* belem’, which is of non-class type ‘int’
   belem->next = NULL;
          ^~~~
buttonlist.h: In member function ‘void ButtonList::Activate_Button(Uint16, Uint16)’:
buttonlist.h:33:10: error: using typedef-name ‘ButtonList::button’ after ‘struct’
   struct button *belem;
          ^~~~~~
buttonlist.h:62:4: note: ‘ButtonList::button’ has a previous declaration here
  } button;
    ^~~~~~
buttonlist.h:35:27: error: cannot convert ‘ButtonList::button*’ to ‘int*’ in assignment
   for ( belem=button_list.next; belem; belem=belem->next ) {
                           ^~~~
buttonlist.h:35:53: error: request for member ‘next’ in ‘* belem’, which is of non-class type ‘int’
   for ( belem=button_list.next; belem; belem=belem->next ) {
                                                     ^~~~
buttonlist.h:36:22: error: request for member ‘x1’ in ‘* belem’, which is of non-class type ‘int’
    if ( (x >= belem->x1) && (x <= belem->x2) &&
                      ^~
buttonlist.h:36:42: error: request for member ‘x2’ in ‘* belem’, which is of non-class type ‘int’
    if ( (x >= belem->x1) && (x <= belem->x2) &&
                                          ^~
buttonlist.h:37:22: error: request for member ‘y1’ in ‘* belem’, which is of non-class type ‘int’
         (y >= belem->y1) && (y <= belem->y2) ) {
                      ^~
buttonlist.h:37:42: error: request for member ‘y2’ in ‘* belem’, which is of non-class type ‘int’
         (y >= belem->y1) && (y <= belem->y2) ) {
                                          ^~
buttonlist.h:38:17: error: request for member ‘callback’ in ‘* belem’, which is of non-class type ‘int’
     if ( belem->callback )
                 ^~~~~~~~
buttonlist.h:39:15: error: request for member ‘callback’ in ‘* belem’, which is of non-class type ‘int’
      (*belem->callback)();
               ^~~~~~~~
buttonlist.h: In member function ‘void ButtonList::Delete_Buttons()’:
buttonlist.h:45:10: error: using typedef-name ‘ButtonList::button’ after ‘struct’
   struct button *belem, *btemp;
          ^~~~~~
buttonlist.h:62:4: note: ‘ButtonList::button’ has a previous declaration here
  } button;
    ^~~~~~
buttonlist.h:47:27: error: cannot convert ‘ButtonList::button*’ to ‘int*’ in assignment
   for ( belem=button_list.next; belem; ) {
                           ^~~~
buttonlist.h:49:19: error: request for member ‘next’ in ‘* belem’, which is of non-class type ‘int’
    belem = belem->next;
                   ^~~~
load.h: In member function ‘const char* LibPath::Path(const char*)’:
<command-line>: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
load.h:95:16: note: in expansion of macro ‘LIBDIR’
    directory = LIBDIR;
                ^~~~~~

**Comment by zerojay** [comment]
Moved to Unstable, must be fixed upstream.

**Comment by macollin123** [comment]
Thank you very much for looking into this so quickly. I will reach out to the contact from this page https://www.libsdl.org/projects/Maelstrom/ and report back if I hear anything.
