### ISSUE TITLE
DevilutionX from prebuild

### ISSUE THREAD

**Issue by AJenbo** [zerojay/RetroPie-Extra#328]
https://github.com/zerojay/RetroPie-Extra/blob/a8e5eebcd992d0b5691f4729d220084e4edb5713/scriptmodules/ports/devilutionx.sh#L20

Woudn't it be faster to download the prebuild armhf release? With that the dependencies would also be limsted to just libsdl2-mixer and libsdl2-ttf.

With the latest release you can also specify the save dir so you don't need to copy the dir to "$md_conf_root/devilutionx", instead just specify --save-dir like you do with --data-dir already

**Comment by zerojay** [comment]
1. Not really much faster at all, to be honest. It compiles fairly quickly though compilation speed is not generally a concern of mine to begin with unless it is prohibitively long. Generally speaking, I'd prefer not to use prebuilt binaries as they require more maintenance to deal with. If you want to use them, be my guest.

2. Copying configs/save files to $md_conf_root is a standard for RetroPie and it's what users expect, so that's not something I'm going to change here unless I'm misunderstanding something.

**Comment by AJenbo** [comment]
2. I'm saying you can have the game save directly in $md_conf_root and avoid having to copy between the two folders.

**Comment by zerojay** [comment]
Thanks, I appreciate the heads up.
